const actionTypes = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    LOGIN_WITH_STUDENT_SUCCESS: 'LOGIN_WITH_STUDENT_SUCCESS',
    LOGIN_WITH_TEACHER_SUCCESS: 'LOGIN_WITH_TEACHER_SUCCESS',

    LOGIN_FAIL: 'LOGIN_FAIL',

    LOGOUT: 'LOGOUT',

    GET_CURRENT: 'GET_CURRENT'
}

export default actionTypes